name: Update kultur-im-kaff.xweb.ch
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        password: ${{ secrets.PASSWORD_PROD }}
        port: ${{ secrets.PORT }}
        script:
          cd sites/kultur-im-kaff.xweb.ch &&
          git fetch --all &&
          git reset --hard origin/master && 
          git submodule update --init --recursive
